# Generated by Django 6.0.3 on 2026-04-02 18:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('options', models.JSONField(default=dict)),
                ('link', models.URLField(max_length=2048)),
                ('source', models.CharField(choices=[('unkn', 'Unknown'), ('ebay', 'eBay'), ('amzn', 'Amazon'), ('alix', 'AliExpress'), ('wbrs', 'WildBerries')], default='unkn', max_length=4)),
                ('external_id', models.CharField(default='000', help_text='Unique identifier from the source platform (e.g. ASIN for Amazon, item number for eBay).', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('styled_name', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.SmallIntegerField(choices=[(1, 'Shipping'), (2, 'Tax'), (3, 'Import Duty'), (4, 'Service Fee'), (5, 'Other')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='main.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.SmallIntegerField(choices=[(0, 'Image'), (1, 'Video')], default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='item_media/%Y/%m/')),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.item')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (e.g. 15.00 means 15%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rating_count', models.PositiveIntegerField(blank=True, help_text='Number of users who submitted a rating', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.item')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'get_latest_by': 'recorded_at',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('unkn', 'Unknown'), ('ebay', 'eBay'), ('amzn', 'Amazon'), ('alix', 'AliExpress'), ('wbrs', 'WildBerries')], default='unkn', max_length=4)),
                ('profile_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'source')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='main.seller'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='main.tag'),
        ),
    ]
