# Generated by Django 6.0.3 on 2026-04-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('source', 'external_id')},
        ),
    ]
