# Generated by Django 6.0.3 on 2026-04-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_currency_currencyexchangeratehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
