# Generated by Django 6.0.3 on 2026-04-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_currency_country_name_alter_currency_symbol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'managed': False, 'verbose_name_plural': 'Currencies'},
        ),
    ]
