# Generated by Django 6.0.3 on 2026-04-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_currency_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterField(
            model_name='currencyexchangeratehistory',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
