# Generated by Django 6.0.3 on 2026-04-19 08:21

from nanoid import generate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='id',
            field=models.CharField(default=generate, editable=False, max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemmedia',
            name='id',
            field=models.CharField(default=generate, editable=False, max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recordeddata',
            name='id',
            field=models.CharField(default=generate, editable=False, max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.CharField(default=generate, editable=False, max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.CharField(default=generate, editable=False, max_length=21, primary_key=True, serialize=False),
        ),
    ]
