# Generated by Django 6.0.3 on 2026-04-25 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_fee_id_alter_itemmedia_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='new_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='main.currency'),
        ),
        migrations.AddField(
            model_name='recordeddata',
            name='new_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.currency'),
        ),
    ]
