# Generated by Django 6.0.3 on 2026-04-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_fee_new_currency_recordeddata_new_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='new_currency',
            new_name='currency_object',
        ),
        migrations.RenameField(
            model_name='recordeddata',
            old_name='new_currency',
            new_name='currency_object',
        ),
    ]
